parameters:
#    backend_android.example.class: Backend\AndroidBundle\Example

services:
#    backend_android.example:
#        class: %backend_android.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
