homepage:
    pattern:  /
    defaults: { _controller: FrontendAndroidBundle:Main:index }

#=======================================================================================================================
frontend_content:
    pattern:  /content/{page}
    defaults: { _controller: FrontendAndroidBundle:Content:showAll, page: 1}
    requirements:
        page:  \d+

frontend_content_new:
    pattern:  /content/new/{page}
    defaults: { _controller: FrontendAndroidBundle:Content:showNew, page: 1}
    requirements:
        page:  \d+

frontend_content_top:
    pattern:  /content/top/{page}
    defaults: { _controller: FrontendAndroidBundle:Content:showTop, page: 1}
    requirements:
        page:  \d+

frontend_content_element:
    pattern:  /content/{slug}
    defaults: { _controller: FrontendAndroidBundle:Content:showElement}

frontend_content_by_category:
    pattern:  /content/category/{slug}
    defaults: { _controller: FrontendAndroidBundle:Content:showAllByCategory}

frontend_content_by_developer:
    pattern:  /content/developer/{slug}
    defaults: { _controller: FrontendAndroidBundle:Content:showAllByDeveloper}