parameters:
#    frontend_android.example.class: Frontend\AndroidBundle\Example

services:
#    frontend_android.example:
#        class: %frontend_android.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
